### PR TITLE
NIFI-685 Proxy support for PostHttp and GetHttp

### PR DESCRIPTION
**Pull request by jahhulbert-ccri**
Allow users to specify and http proxy for post/get http processors

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
i can squash this into one if desired.

**Comment by markap14** [comment]
Andrew,

I've looked over the pull request. Code looks good. Verified that it builds and that it all functions properly as it used to, without using the proxies.

Have you had a chance to test this with an HTTP Proxy? I really have no idea how to test this with an HTTP Proxy, so if you've verified that it works as expected then that's good enough for me and I'll push it :)

**Comment by jahhulbert-ccri** [comment]
@markap14 i did test. I don't have access to a proxy server on the web but I'll work on getting one set up via jetty or apache and then see if i can get a better test. It did work in the environment I need it it so it should be OK to merge!

**Comment by mosermw** [comment]
I have had success using a squid proxy from http://www.squid-cache.org/ for testing similar code against an HTTP proxy.

**Comment by markap14** [comment]
Code looks good, and I have verified that the original functionality still works as designed, so that's good enough for me. Merged to develop. Thanks!

**Pull request closed without merging**
