### PR TITLE
Nifi 280

### PR DESCRIPTION
**Pull request by danbress**
Pull request to resolve NIFI-280

### CODE REVIEW

**Comment by madrob** [comment]
You appear to have some duplicate commits in this, looking solely at the messages. 07477aa..c8158c8 and a753e00..12ba0ca specifically look the same.

**Comment by danbress** [comment]
@madrob, Ok, I see what you are saying.  I'm kind of new to this git thing, so I don't know how that happened or how to resolve it.  Do I want to use git rebase -i and squash my commits?

**Comment by danbress** [comment]
Is there anything I can do to help this along?  I can fix the duplicate commits @madrob mentioned and submit a new pull request if that'll help.  Just let me know.

**Comment by madrob** [comment]
@danbress I started to write a response on how to fix the commits, but it quickly got hairier than I liked. I imagine that the lack of further activity this week has been a side effect of the team trying to push out their first release.

If you have somebody nearby that can pair program with you to fix your git history, that would probably be the most straightforward route. If not, I can try to guide you through it, but the safest advice is always to copy this work into a new branch and mess around there so that you don't lose anything. You'll likely want some combination of `git rebase -i` and maybe `git reset --hard`.

**Comment by danbress** [comment]
@madrob Thanks for the advice.  Just squashed everything in a new branch and submitted a new pull request.  Let me know if this one looks better.

**Pull request closed without merging**
