### PR TITLE
NIFI-152 Dev guide update

### PR DESCRIPTION
**Pull request by danbress**
I made two tiny tweaks(fixed some broken markup, and changed a "." to a ":"), and updated the processor documentation section to reflect the new generated documentation feature.  You'll see a pull request for that shortly.

### CODE REVIEW

**Comment by joewitt** [comment]
There is an apparent space between the s and the preceeding word in two cases.  Is that intentional?  I am not sure about the processor to component switch and associated docs.  Is that related to the new doc generation capability?  Mark P: Is this something you're working with Dan on?  Definitely want to help close tickets and accept patches but this one I don't know much about.

thanks dan

**Comment by danbress** [comment]
Joe,
The space is not intentional per se, but without it the monospace markup
doesn't show up. So we might want to pick one(monospace no 's') or the
other ('s' with no monospace) or figure out how to do both!

I may have used the word component instead of processor in the section I
added to reflect that the documentation applies to all configurable
components(Processors, ControllerServices and ReportingTasks) and not just
processors.

It might not make sense to merge this until my other pull request is
merged. I'm working on incorporating Mark's suggestions on that on this
weekend.

Dan

**Comment by danbress** [comment]
I figured out how to get rid of the space in the html(use ++monospace++s instead of `monospace`s), but now the CSS is padding <code> elements, and I'm not sure how to use their existing stylesheet and only modify that one property.  They seem to be embedding the stylesheet.

**Comment by danbress** [comment]
OK, to solve the issue with the space between monospace and s I did the following:

1) copied the asciidoc default stylesheet into our codebase
2) uncommented a line to import the google web fonts css
3) modified the copied asciidoc css to remove trailing padding on < code > elements
4) modified the pom to use the copied asciidoc css

Looks good now!

My very limited understanding of the MIT license reads that we can copy/modify/distribute their asciidoc css with our product so long as include the copyright and the license.  So does this mean as long as the license and copyright are in the ascii-mod.css we are good?  Is there more to it than that?

**Comment by joewitt** [comment]
Regarding licensing I believe you are quite right.  So easily managed.

I don't fully follow the two threads you're working and the branching thing so not quite sure where to go from here.  Maybe kill both threads and just have one overarching one for your work so it can be merged as a unit.  Does that seem fine?  I am happy to help do the licensing part if you like or you can take a crack at it.  I put up a licensing guidance thing on the nifi website (horrifically wordy i realize) that may be of use.

Thanks!
Joe

**Comment by danbress** [comment]
Joe,
   Cool, thanks for licensing guidence.  I just pushed my change... but I need to read the licensing stuff you wrote to make sure this is in compliance.  Will do that after lunch.

   If merging these two things into one is easier I'm happy to do that.  I didn't originally intend for them to be dependent, and they don't modify the same files.  But at this point the content of the changes of this one reflect changes that have happened in the other.  Let me know whats best and I'll do it.

Dan

**Comment by joewitt** [comment]
dan - no problem.  I take care of the license adjustment and don't combine
the tickets unless it makes sense.  I wasn't sure but based on what you
wrote sounds like you were on the right track already.

thanks
joe

**Pull request merged**
