### PR TITLE
NIFI-344 - Remote processor group lets you specify protocols other than http/https

### PR DESCRIPTION
**Pull request by danbress**
On the front end, providing a placeHolder hint as to what the expected value looks like
On the back end validating that the user specified url(on create or update) is http://something or https://something

### CODE REVIEW

**Comment by mcgilman** [comment]
Cool! Didn't know about the placeholder attribute. I've been doing that myself using focus/blur events and css. The only downside is that it isn't supported in IE9 (which technically we do support). However, I think it's a fair tradeoff, so I'll put in a ticket to switch usage to placeholder everywhere.

**Comment by danbress** [comment]
Thanks.  I wanted to ask you about the placeholder attribute, since it is new to HTML5, and wasn't sure how far back we were supporting.

Do we have a list of the minimum browsers/standards that are required to run the app?

**Comment by danbress** [comment]
Just poked through the website, didn't see what I was looking for in terms of "minimum system requirements" to run the software.  Just something about maven and JDK on the development page.  So I created a ticket NIFI-370

**Comment by mcgilman** [comment]
Those details used to be in the user guide but I don't see it in the version that was put into 0.0.1. It should go where ever we've documented other minimum requirements (JVM version, etc).

To answer the question directly, the limiting factor for browsers is SVG support. IE introduced support for SVG in IE 9.

**Pull request merged**
